# Generated by Django 4.2.1 on 2023-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Активна', 'Активна'), ('Не активна', 'Не активна')], default='Не активна', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Создатель'),
        ),
    ]
