# Generated by Django 4.2.1 on 2023-07-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_status_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='is_active',
            new_name='actual_version',
        ),
    ]
