# Generated by Django 4.2.1 on 2023-07-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_is_active_version_actual_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='product',
            new_name='name_of_product',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='version_number',
            new_name='number_of_version',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='name',
            new_name='title_of_version',
        ),
    ]
